server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/sionic?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(jec8vKAsSeZpbjjIinQpjQ==)
    password: ENC(MtsXD0psWswgmYbrY5u1iw==)

jwt:
  secret: ENC(XoNzoPVD2ltlIjiOpLyGM/tyepsQWzQ3FYEbu1Y8snWM+PEWobqMpkaD9+IXiVPR16JruwhLWzXdVDpJy/UDIA==)
  access-token-expiration-time: 900000  # 15? 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2? 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

jasypt:
  encryptor:
    password: ${PASSWORD}
